version: '3.8'

services:
  fida-web:
    image: fida-web:latest # This will be replaced by the CI/CD pipeline if using a registry
    container_name: fida-web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
